version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules

# No volumes needed since we're using MongoDB Atlas